basic_escape ::= (([\"\\/bfnrt]) | ("u" [A-Fa-f0-9] [A-Fa-f0-9] [A-Fa-f0-9] [A-Fa-f0-9]))
basic_string_sub ::= (("\"") | ([^\0-\x1f\"\\\r\n] basic_string_sub) | ("\\" basic_escape basic_string_sub)) (=([ \n\r\t]* [,}\]:]))
basic_any ::= ((basic_number) | (basic_string) | (basic_boolean) | (basic_null) | (basic_array) | (basic_object))
basic_integer ::= (("0") | (basic_integer_1 [1-9] [0-9]*))
basic_number ::= ((basic_number_1 basic_number_2 basic_number_3 basic_number_5))
basic_string ::= (("\"" basic_string_sub))
basic_boolean ::= (("true") | ("false"))
basic_null ::= (("null"))
basic_array ::= (("[" basic_any basic_array_items{0, -1} "]") | ("[" "]"))
basic_object ::= (("{" basic_string ": " basic_any basic_object_properties{0, -1} "}") | ("{" "}"))
basic_number_digits ::= (([0-9]))
basic_array_items ::= ((", " basic_any))
basic_object_properties ::= ((", " basic_string ": " basic_any))
root ::= (("{" "\"adjusted_volatile_messages\"" ": " root_prop_0 root_part_0 "}"))
root_prop_0 ::= (("[[\"system\",\"Preserve evidence evidence.\"],[\"user\",\"Keep my exact request and punctuation: {a:1}.\"]]"))
root_prop_1 ::= (("[" "]"))
root_prop_3 ::= (("[" root_prop_3_additional root_prop_3_items{0, -1} "]") | ("[" "]"))
root_prop_3_additional ::= ((root_prop_3_additional_case_0) | (root_prop_3_additional_case_1))
root_prop_3_additional_case_0 ::= (("{" "\"class_code\"" ": " root_prop_3_additional_case_0_prop_0 root_prop_3_additional_case_0_part_0 "}"))
root_prop_3_additional_case_0_prop_0 ::= (("21"))
root_prop_3_additional_case_0_prop_1 ::= (("{" "\"name\"" ": " basic_string root_prop_3_additional_case_0_prop_1_part_0 "}"))
root_prop_3_additional_case_0_prop_1_prop_2 ::= ((basic_string) | (basic_null))
root_prop_3_additional_case_0_prop_1_prop_5 ::= (("[" basic_string root_prop_3_additional_case_0_prop_1_prop_5_items{9, -1} "]"))
root_prop_3_additional_case_0_prop_1_prop_5_items ::= ((", " basic_string))
root_prop_3_additional_case_0_prop_1_prop_8 ::= ((basic_object) | (basic_null))
root_prop_3_additional_case_0_prop_1_part_7 ::= ((", " "\"dependency_registry\"" ": " root_prop_3_additional_case_0_prop_1_prop_8))
root_prop_3_additional_case_0_prop_1_part_6 ::= ((", " "\"variants\"" ": " basic_array root_prop_3_additional_case_0_prop_1_part_7))
root_prop_3_additional_case_0_prop_1_part_5 ::= ((", " "\"step_descriptions\"" ": " basic_array root_prop_3_additional_case_0_prop_1_part_6))
root_prop_3_additional_case_0_prop_1_part_4 ::= ((", " "\"intent_examples\"" ": " root_prop_3_additional_case_0_prop_1_prop_5 root_prop_3_additional_case_0_prop_1_part_5))
root_prop_3_additional_case_0_prop_1_part_3 ::= ((", " "\"prior_knowledge_content\"" ": " basic_string root_prop_3_additional_case_0_prop_1_part_4))
root_prop_3_additional_case_0_prop_1_part_2 ::= ((", " "\"steps\"" ": " basic_array root_prop_3_additional_case_0_prop_1_part_3))
root_prop_3_additional_case_0_prop_1_part_1 ::= ((", " "\"trigger\"" ": " root_prop_3_additional_case_0_prop_1_prop_2 root_prop_3_additional_case_0_prop_1_part_2))
root_prop_3_additional_case_0_prop_1_part_0 ::= ((", " "\"description\"" ": " basic_string root_prop_3_additional_case_0_prop_1_part_1))
root_prop_3_additional_case_0_part_0 ::= ((", " "\"payload\"" ": " root_prop_3_additional_case_0_prop_1))
root_prop_3_additional_case_1 ::= (("{" "\"class_code\"" ": " root_prop_3_additional_case_1_prop_0 root_prop_3_additional_case_1_part_0 "}"))
root_prop_3_additional_case_1_prop_0 ::= (("22"))
root_prop_3_additional_case_1_prop_1 ::= (("{" "\"name\"" ": " basic_string root_prop_3_additional_case_1_prop_1_part_0 "}"))
root_prop_3_additional_case_1_prop_1_part_1 ::= ((", " "\"content\"" ": " basic_string))
root_prop_3_additional_case_1_prop_1_part_0 ::= ((", " "\"description\"" ": " basic_string root_prop_3_additional_case_1_prop_1_part_1))
root_prop_3_additional_case_1_part_0 ::= ((", " "\"payload\"" ": " root_prop_3_additional_case_1_prop_1))
root_prop_3_items ::= ((", " root_prop_3_additional))
root_prop_4 ::= (("[" "]"))
root_prop_5 ::= (("[" "]"))
root_prop_6 ::= (("[" "]"))
root_part_5 ::= ((", " "\"settings_adjustments\"" ": " root_prop_6))
root_part_4 ::= ((", " "\"proposed_recipe_updates\"" ": " root_prop_5 root_part_5))
root_part_3 ::= ((", " "\"proposed_intent_examples\"" ": " root_prop_4 root_part_4))
root_part_2 ::= ((", " "\"proposed_components\"" ": " root_prop_3 root_part_3))
root_part_1 ::= ((", " "\"composition_summary\"" ": " basic_string root_part_2))
root_part_0 ::= ((", " "\"bridge_messages\"" ": " root_prop_1 root_part_1))
basic_integer_1 ::= ("" | ("-"))
basic_number_1 ::= ("" | ("-"))
basic_number_2 ::= (("0") | ([1-9] [0-9]*))
basic_number_3 ::= ("" | ("." basic_number_digits{1, -1}))
basic_number_4 ::= ("" | ([+\-]))
basic_number_5 ::= ("" | ([eE] basic_number_4 basic_number_digits{1, -1}))
