basic_escape ::= (([\"\\/bfnrt]) | ("u" [A-Fa-f0-9] [A-Fa-f0-9] [A-Fa-f0-9] [A-Fa-f0-9]))
basic_string_sub ::= (("\"") | ([^\0-\x1f\"\\\r\n] basic_string_sub) | ("\\" basic_escape basic_string_sub)) (=([ \n\r\t]* [,}\]:]))
basic_any ::= ((basic_number) | (basic_string) | (basic_boolean) | (basic_null) | (basic_array) | (basic_object))
basic_integer ::= (("0") | (basic_integer_1 [1-9] [0-9]*))
basic_number ::= ((basic_number_1 basic_number_2 basic_number_3 basic_number_5))
basic_string ::= (("\"" basic_string_sub))
basic_boolean ::= (("true") | ("false"))
basic_null ::= (("null"))
basic_array ::= (("[" basic_any basic_array_items{0, -1} "]") | ("[" "]"))
basic_object ::= (("{" basic_string ": " basic_any basic_object_properties{0, -1} "}") | ("{" "}"))
basic_number_digits ::= (([0-9]))
basic_array_items ::= ((", " basic_any))
basic_object_properties ::= ((", " basic_string ": " basic_any))
root ::= (("{" "\"task_kind\"" ": " root_prop_0 root_part_0 "}"))
root_prop_0 ::= (("\"python\"") | ("\"recipe\"") | ("\"review\""))
root_prop_1 ::= (("[" root_prop_1_additional root_prop_1_items{0, -1} "]") | ("[" "]"))
root_prop_1_additional ::= (("{" "\"guard\"" ": " basic_string root_prop_1_additional_part_0 "}"))
root_prop_1_additional_part_0 ::= ((", " "\"result\"" ": " basic_string))
root_prop_1_items ::= ((", " root_prop_1_additional))
root_prop_3 ::= (("[" root_prop_3_additional root_prop_3_items{0, -1} "]") | ("[" "]"))
root_prop_3_additional ::= (("{" "\"knowledge\"" ": " basic_string root_prop_3_additional_part_0 "}"))
root_prop_3_additional_part_0 ::= ((", " "\"uuid\"" ": " basic_string))
root_prop_3_items ::= ((", " root_prop_3_additional))
root_prop_4 ::= (("[" basic_string root_prop_4_items{0, -1} "]") | ("[" "]"))
root_prop_4_items ::= ((", " basic_string))
root_prop_5 ::= (("[" basic_string root_prop_5_items{0, -1} "]") | ("[" "]"))
root_prop_5_items ::= ((", " basic_string))
root_part_5 ::= ((", " "\"notes\"" ": " basic_string))
root_part_4 ::= ((", " "\"prerequisites\"" ": " root_prop_5 root_part_5))
root_part_3 ::= ((", " "\"authorized_edits\"" ": " root_prop_4 root_part_4))
root_part_2 ::= ((", " "\"workflow\"" ": " root_prop_3 root_part_3))
root_part_1 ::= ((", " "\"helper_required\"" ": " basic_boolean root_part_2))
root_part_0 ::= ((", " "\"branches\"" ": " root_prop_1 root_part_1))
basic_integer_1 ::= ("" | ("-"))
basic_number_1 ::= ("" | ("-"))
basic_number_2 ::= (("0") | ([1-9] [0-9]*))
basic_number_3 ::= ("" | ("." basic_number_digits{1, -1}))
basic_number_4 ::= ("" | ([+\-]))
basic_number_5 ::= ("" | ([eE] basic_number_4 basic_number_digits{1, -1}))
